# Generated by Django 6.0.5 on 2026-05-27 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_notification_review_schedule_slot_user_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='appointment',
            table='appointments',
        ),
        migrations.AlterModelTable(
            name='doctor',
            table='doctors',
        ),
        migrations.AlterModelTable(
            name='patient',
            table='patients',
        ),
    ]
